type Query {
  repo(owner: String!, repo: String!): Repo
}

type Repo {
  owner: String
  name: String
  contents(ref: String!, path: String, match: String): [Resource]
}

enum Type {
  FOLDER
  FILE
}

type Resource {
  path: String
  name: String
  type: Type
  ref: String
}